#install python and ansible on host before doing any of this
- name: Generate Key on the localhost
  hosts: localhost
  become: yes
  roles:
    - key_generator

- name: Distribute keys to cluster nodes
  hosts: cluster_nodes
  become: yes
  roles:
    - key_distributor

- name: install dependencies
  hosts: cluster_nodes
  become: yes
  roles:
    - install_dependencies

