#install python and ansible on host before doing any of this
- name: Generate Key on the localhost
  hosts: localhost
  become: yes
  roles:
    - key_generator

- name: Distribute keys to cluster nodes
  hosts: cluster_nodes:client
  become: yes
  roles:
    - key_distributor

- name: prepare disk on cluster nodes
  hosts: cluster_nodes:client
  roles:
    - mount_disk

- name: install dependencies
  hosts: cluster_nodes:client
  become: yes
  roles:
    - install_dependencies

- name: Download db on the client
  hosts: client
  become: yes
  roles:
    - data

- name: Distribute the file to other clients
  hosts: cluster_nodes
  #become: yes
  roles:
    - data_distributer
  vars:
    src_file: "/home/ec2-user/data/weights.tar.gz"
    dest_dir: "/home/ec2-user/data/"
    delegate: "10.0.7.13"

- name: Distribute scripts to other clients
  hosts: cluster_nodes:client
  become: yes
  roles:
    - script_distributer
  vars:
    src_file: "/home/ec2-user/cw0235/scripts"
    dest_dir: "/home/ec2-user/"
