#install python and ansible on host before doing any of this
- name: Generate Key on the localhost
  hosts: localhost
  become: yes
  roles:
    - key_generator

- name: Distribute keys to cluster nodes
  hosts: cluster_nodes:client
  become: yes
  roles:
    - key_distributor

- name: prepare disk on cluster nodes
  hosts: cluster_nodes:client
  roles:
    - mount_disk

- name: install dependencies
  hosts: cluster_nodes:client
  become: yes
  roles:
    - install_dependencies



- name: Download db on the client
  hosts: client
  become: yes
  roles:
    - data

- name: Delete the hhsuite archive
  hosts: cluster_nodes:client
  tasks:
    - name: Delete specified files
      file:
        path: "/home/ec2-user/data/{{ item }}"
        state: absent
      loop:
        - hhr_parse.out 
 
- name: Check if pdb70 archive exists
  hosts: client
  tasks:
    - name: Check if pdb70 archive exists
      stat:
        path: /home/ec2-user/data/pdb70/md5sum
      register: pdb70

    - name: create a pdb70 folder
      ansible.builtin.file:
        path: /home/ec2-user/data/pdb70
        state: directory
        mode: '0755'
      when: not pdb70.stat.exists

    - name: Unzip pdb70
      ansible.builtin.unarchive:
        src: /home/ec2-user/data/pdb70_from_mmcif_latest.tar.gz
        dest: /home/ec2-user/data/pdb70/
        remote_src: yes
      when: not pdb70.stat.exists

- name: Distribute the file to other clients
  hosts: cluster_nodes
  tasks:
    - name: Check if pdb70 archive exists
      stat:
        path: /home/ec2-user/data/pdb70/pdb70_a3m.ffdata
      register: pdb70

    - name: Distribute
      include_role:
        name: data_distributer
      vars:
        src_file: "/home/ec2-user/data/pdb70"
        dest_dir: "/home/ec2-user/data/"
        delegate: "10.0.7.13"
      when: not pdb70.stat.exists

- name: Distribute scripts to other clients
  hosts: cluster_nodes:client
  become: yes
  roles:
    - script_distributer
  vars:
    src_file: "/home/ec2-user/cw0235/scripts"
    dest_dir: "/home/ec2-user/"
  
- name: Distribute full list of experiment ids
  hosts: cluster_nodes:client
  become: yes
  roles:
    - script_distributer
  vars:
    src_file: "/home/ec2-user/cw0235/experiment_ids.txt"
    dest_dir: "/home/ec2-user/scripts/experiment_ids.txt"
  
- name: Dividing work
  hosts: cluster_nodes:client
  become: yes
  roles:
    - divide_work

- name: Calculate line ranges for each node
  hosts: localhost
  tasks:
    - name: Initialize an empty list for line ranges
      set_fact:
        line_ranges: []

    - name: Calculate line ranges
      set_fact:
        line_ranges: "{{ line_ranges + [{'host': item, 'start_line': start_line, 'end_line': end_line if not ansible_loop.last else hostvars[item].line_count}] }}"
      vars:
        start_line: "{{ ((prev_end_line | default(0)) | int) + 1 }}"
        end_line: "{{ (start_line | int) + ((((hostvars[item].ansible_processor_vcpus | int) - 1) * (hostvars[item].line_count | int) / (hostvars[item].total_threads | int)) | round(0, 'floor')) - 1 }}"
        prev_end_line: "{{ line_ranges | map(attribute='end_line') | last }}"
      loop: "{{ groups['cluster_nodes'] + groups['client'] }}"
      loop_control:
        extended: yes
      run_once: true


  
- name: Distribute line ranges to nodes
  hosts: cluster_nodes:client
  become: yes
  tasks:
    - name: Set line range for each node
      set_fact:
        node_line_start: "{{ host_line_range.start_line }}"
        node_line_end: "{{ host_line_range.end_line }}"
      vars:
        host_line_range: "{{ hostvars['localhost'].line_ranges | selectattr('host', 'equalto', inventory_hostname) | first }}"
    - name: Display line ranges for each node
      debug:
        msg: "Node {{ inventory_hostname }} processes lines from {{ hostvars[inventory_hostname].node_line_start }} to {{ hostvars[inventory_hostname].node_line_end }}"
    - name: Create a file with new ids
      ansible.builtin.shell: "awk 'NR >= {{hostvars[inventory_hostname].node_line_start}} && NR <= {{hostvars[inventory_hostname].node_line_end}}' /home/ec2-user/scripts/experiment_ids.txt > /home/ec2-user/scripts/partial_ids.txt"

- name: Execute a Python script on remote nodes
  hosts: cluster_nodes:client
  tasks:
    - name: Run Python script
      ansible.builtin.command: python3 /home/ec2-user/scripts/pipeline_script.py /home/ec2-user/scripts/uniprotkb_proteome_UP000005640_2023_10_05.fasta /home/ec2-user/scripts/partial_ids.txt
  
- name: Prepare and results master file
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create file and add header line
      ansible.builtin.copy:
        dest: "/home/ec2-user/cw0235/all_results.txt"
        content: "query_id,best_hit,best_evalue,best_score,score_mean,score_std,score_gmean\n"
        force: no

- name: Fetch files from remote nodes and combine into a master file
  hosts: cluster_nodes:client
  gather_facts: true

  tasks:
    - name: Fetch file from remote node
      ansible.builtin.fetch:
        src: /home/ec2-user/hhr_parse.out
        dest: /home/ec2-user/cw0235/{{ inventory_hostname }}/
        flat: yes

    - name: Concatenate contents on the control node
      ansible.builtin.shell: "cat /home/ec2-user/cw0235/{{ item }}/hhr_parse.out >> /home/ec2-user/cw0235/all_results.txt"
      loop: "{{ ansible_play_hosts }}"
      delegate_to: localhost
      run_once: true
