- name: python
  ansible.builtin.dnf:
    name: 
          - python3
          - python3-pip
- name: install python dependencies
  ansible.builtin.pip:
    name: biopython, scipy, numpy
- name: install torch
  ansible.builtin.command: pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
  