
- name: Collect only the hardware related facts
  ansible.builtin.setup:
    gather_subset:
      - hardware

- name: Display number of CPU threads
  debug:
    var: ansible_processor_vcpus

#unholy one-liner, but works okay!
- name: Set fact for total number of threads for processing
  set_fact:
    total_threads: "{{ ((groups['cluster_nodes'] + groups['client']) | map('extract', hostvars, 'ansible_processor_vcpus') | map('int') | sum) - ((groups['cluster_nodes'] + groups['client']) | length)}}"

- name: Display total number of CPU threads across all nodes
  debug:
    var: total_threads
  run_once: true

- name: Count the number of lines in the file
  command: wc -l /home/ec2-user/scripts/experiment_ids.txt
  register: n_ids

- name: Set line count as a fact
  set_fact:
    line_count: "{{ (n_ids.stdout.split(' ')[0] | int) + 1}}"
  
- name: Display number of ids to process
  debug:
    var: line_count
  run_once: true


#- name: generate a partial manifest on each client
  #ansible.builtin.shell: "awk '!((NR+{{rank}}) %{{total_threads}})' manifest.txt > manifest_local.txt"