- name: Check if a folder exists
  ansible.builtin.stat:
    path: "{{ dest_dir }}"
  register: f_stat

- name: Copy file to remote node
  ansible.builtin.copy:
    src:  "{{ src_file }}"
    dest: "{{ dest_dir }}"
  when: not f_stat.stat.exists